version: '3.9'

services:
  database:
    image: postgres:15.0-alpine
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - backend_nw
    env_file:
      - src/.env
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  pg_data_todolist:

networks:
  backend_nw:
    driver: bridge
